//========AUTH==========
export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
export const VERIFY_PATTERNS = 'VERIFY_PATTERNS';
export const CLEAR_VERIFICATIONS = 'CLEAR_VERIFICATIONS';
export const LOGIN = 'LOGIN';
export const SIGNUP_WITH_EMAIL_AND_PASSWORD = 'SIGNUP_WITH_EMAIL_AND_PASSWORD';
export const CHECK_LOCALSTORAGE_AUTH = 'CHECK_LOCALSTORAGE_AUTH';


// ==========BLOG==============
export const CLEAR_BLOG_DETAILS = 'CLEAR_BLOG_DETAILS';
export const ADD_POST = 'ADD_POST';
export const UPDATE_BLOG_CREDENTIALS = 'UPDATE_BLOG_CREDENTIALS';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';