//========AUTH==========
export const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
export const VERIFY_PATTERNS = 'VERIFY_PATTERNS';
export const CLEAR_VERIFICATIONS = 'CLEAR_VERIFICATIONS';
export const LOGIN = 'LOGIN';
export const SIGNUP_WITH_EMAIL_AND_PASSWORD = 'SIGNUP_WITH_EMAIL_AND_PASSWORD';
export const CHECK_LOCALSTORAGE_AUTH = 'CHECK_LOCALSTORAGE_AUTH';


// ==========BLOG==============
export const CLEAR_BLOG_DETAILS = 'CLEAR_BLOG_DETAILS';
export const UPDATE_BLOG_CREDENTIALS = 'UPDATE_BLOG_CREDENTIALS';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const GET_ALL_BLOGS = 'GET_ALL_BLOGS';
export const SET_USERS_BLOGS = 'SET_USERS_BLOGS';

// ===============USER=========
export const SET_USER = 'SET_USER';
export const SET_AUTH_USER = 'SET_AUTH_USER';